### ISSUE TITLE
Error (java.lang.ExceptionInInitializerError) running `gradlew` on Linux Mint 18 on MacBook Pro

### ISSUE THREAD

**Issue by drhuffman12** [crystal-lang-tools/intellij-crystal#1]
After I cloned the repo and ran `gradlew` inside the repo folder, it errors out w/ `java.lang.ExceptionInInitializerError`. (FYI, instead of `~`, you would see `/home/<username>`.) See below:

```
$ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-3.1-all.zip
...
Unzipping ~/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1-all.zip to ~/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74
Set executable permissions for: ~/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

```
$ chmod +x ~/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1/bin/gradle

$ ./gradlew --debug --stacktrace
10:17:12.336 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: ~/.gradle/native
10:17:12.461 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:17:12.463 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:17:12.464 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:17:12.464 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
10:17:12.465 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.ExceptionInInitializerError (no error message)
10:17:12.466 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
10:17:12.466 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] java.lang.ExceptionInInitializerError
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultClassLoaderRegistry.restrictToGradleApi(DefaultClassLoaderRegistry.java:48)
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultClassLoaderRegistry.java:31)
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoaderRegistry(GlobalScopeServices.java:208)
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:17:12.467 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.invoke(Method.java:543)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry.invoke(DefaultServiceRegistry.java:462)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry.access$1200(DefaultServiceRegistry.java:84)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:796)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:752)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:589)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:634)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:253)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:214)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:352)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.BuildActionsFactory.createGlobalClientServices(BuildActionsFactory.java:148)
10:17:12.468 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.BuildActionsFactory.runBuildWithDaemon(BuildActionsFactory.java:108)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActionsFactory.java:83)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.createAction(CommandLineActionFactory.java:249)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.Main.doAction(Main.java:33)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:17:12.469 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.invoke(Method.java:543)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.invoke(Method.java:543)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @5d99c6b5
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:207)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:34)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:38)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:224)
10:17:12.470 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:48)
10:17:12.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 46 more
10:17:12.471 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 

```

My version info is:
```
$ uname -srvmpio
Linux 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+152)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+152, mixed mode)

$ ~/.gradle/wrapper/dists/gradle-3.1-all/ejgglywf033yp6s4x8ahmgm74/gradle-3.1/bin/gradle -version

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          9-ea (Oracle Corporation 9-ea+152)
OS:           Linux 4.4.0-59-generic amd64
```

**Comment by s5bug** [comment]
This is a problem with the code being unfinished. I am working on fixes now and will make a PR when finished.

**Comment by s5bug** [comment]
I have no idea what I did, but I know this problem is with gradle not compiling BNF files correctly. Jar that works:
[intellij-crystal_jar.zip](https://github.com/intellij-crystal/intellij-crystal/files/1202960/intellij-crystal_jar.zip)
Install using Install Plugin From Disk in the plugins menu.

EDIT: Whoops! That zip doesn't have any class files in it 😓 This one does 😄 
[intellij-crystal_jar.zip](https://github.com/intellij-crystal/intellij-crystal/files/1202962/intellij-crystal_jar.zip)
